### ISSUE TITLE
Save output to json or csv data file?

### ISSUE THREAD

**Issue by laryan61** [jaebradley/rotten_tomatoes_cli#15]
If the data was available in a format that could then allow users to import in their own scripts. That would be a nice option.

**Comment by jaebradley** [comment]
@laryan61 would [the `rotten_tomatoes_client`](https://github.com/jaebradley/rotten_tomatoes_client) be helpful?

**Comment by laryan61** [comment]
I’ve reviewed the code at github.com. And yes I think it will work for what I need. Thanks.

I do have one other question. In your example code you perform a search for “Indiana Jones”, which returns multiple movies. Is it possible to refine the search to return just a particular Indiana Jones movie? By including the Release Year in the search?




Lee Ryan
President, NexLynx, Inc
123 SW 6th Ave, Suite 100
Topeka, KS 66603
Tel: 785.232.5969 / Fax: 866.894.7209

[Visit our Facebook Page]<http://www.facbook.com/NexLynxInc>[Visit our Twitter Feed]<http://www.twitter.com/Nexlynx>[Visit our LinkedIn Profile]<https://www.linkedin.com/company/2060059?trk=prof-exp-company-name>

Discover the IT Difference

[Visit our Website]<http://www.nexlynx.com/>
Topeka's Oldest Web Hosting and Web Design Provider<http://www.topekawebdesign.com/>

**Comment by jaebradley** [comment]
I'm not sure it's possible to search for movies by release date via Rotten Tomatoes. If you find a way, please let me know!

I think this issue can be closed - feel free to reopen.
